automation:
  - id: "1695593856113"
    # Fires whenever a door Command Class 99 status update occurs
    triggers:
      - trigger:
          - platform: zwave_js.value_updated
            # At least one `device_id` or `entity_id` must be provided
            entity_id:
              - lock.front_door_lock
            # `property` and `command_class` are required
            command_class: 98 # Door Lock CC
            property: "latchStatus"
            # `from` and `to` will both accept lists of values and the trigger will fire if the value update matches any of the listed values
            from:
              - "closed"
              - "jammed"
              - "opened"
            to:
              - "opened"
              - "closed"
      - trigger:
          - platform: zwave_js.value_updated
            # At least one `device_id` or `entity_id` must be provided
            entity_id:
              - lock.front_door_lock
            # `property` and `command_class` are required
            command_class: 99 # Door Lock CC
            property: "userCode"
            propertyName: "userCode"
            # `property_key` and `endpoint` are optional
            #property_key: 4
            #endpoint: 0
    conditions: []
    actions:
      - action: input_text.set_value
        data:
          value: "{{ trigger.event.data | to_json }}"
        target:
          entity_id: input_text.kb_test_data_1
